# Generated by Django 5.0.3 on 2025-12-10 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_intakesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of availability')),
                ('start_time', models.TimeField(help_text='Start time (e.g., 14:00)')),
                ('end_time', models.TimeField(help_text='End time (e.g., 15:00)')),
                ('slot_type', models.CharField(choices=[('initial', 'Initial Consultation'), ('followup', 'Follow-up'), ('general', 'General')], default='initial', help_text='Type of consultation', max_length=50)),
                ('is_available', models.BooleanField(default=True, help_text='Whether this slot is currently bookable')),
                ('notes', models.TextField(blank=True, help_text='Internal notes (not visible to public)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Availability Slot',
                'verbose_name_plural': 'Availability Slots',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='BookingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Client name', max_length=120)),
                ('email', models.EmailField(help_text='Client email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Client phone number (optional)', max_length=50)),
                ('description', models.TextField(help_text='Brief description of the matter')),
                ('is_paid', models.BooleanField(default=False, help_text='Whether payment has been received')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(help_text='The availability slot being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='pages.availabilityslot')),
            ],
            options={
                'verbose_name': 'Booking Submission',
                'verbose_name_plural': 'Booking Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
